# Generated by Django 5.0.2 on 2024-02-28 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosAdquisicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capa', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
                ('env', models.CharField(max_length=100, null=True)),
                ('nombre_file', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_adquisicion', models.DateTimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('id_embalse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.embalses')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
                ('id_metodo_adquisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.metodosadquisicion')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
                ('id_tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.tiporecurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursosGenerados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('env', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('capa', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
                ('nombre_file', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('id_embalse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.embalses')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
                ('id_recurso_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurso_generado_1', to='recursos.recursos')),
                ('id_recurso_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurso_generado_2', to='recursos.recursos')),
                ('id_tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.tiporecurso')),
            ],
        ),
    ]
