# Generated by Django 5.0.2 on 2024-03-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('proyectos', '0001_initial'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('proyectos', models.CharField(max_length=100)),
                ('ukey', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('nombres', models.TextField()),
                ('dems', models.TextField()),
                ('ids', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('id_embalse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.embalses')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
            ],
        ),
    ]
