# Generated by Django 5.0.2 on 2024-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_perfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='geojson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
