# Generated by Django 5.0.2 on 2024-03-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('recursos', '0003_perfiles_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='id_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas'),
        ),
    ]
