# Generated by Django 5.0.2 on 2024-02-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('emal_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
